bppackaging/src/objects/Accounting_Data_Migration__c.object
<CustomObject>
    <fields>
        <fullName>Last_Synched_Date__c</fullName>
        <label>Last Synched Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Accounting Data Migration</label>
    <nameField>
        <displayFormat>AM-{000}</displayFormat>
        <label>Accounting Data Migration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accountings Data Migration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bppackaging/src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Inventory_GL__c</fullName>
        <label>Inventory GL</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Expense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Labour</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sublet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bppackaging/src/objects/CO_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>CO Line Items</relationshipLabel>
        <relationshipName>CO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CO Line Item</label>
    <nameField>
        <displayFormat>COLI-{00000000}</displayFormat>
        <label>CO Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

bppackaging/src/objects/GL_Account__c.object
<CustomObject>
    <fields>
        <fullName>MYOB_Account_Name__c</fullName>
        <label>MYOB Account Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MYOB_Account_Number__c</fullName>
        <label>MYOB Account Number</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Deposit Account</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Deposit Allocation Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Invoice Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received Inventory Accrual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>GL Account</label>
    <nameField>
        <displayFormat>GLA-{00000}</displayFormat>
        <label>GL Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bppackaging/src/objects/Part__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part_ID__c</fullName>
        <description>Merge of Part Number and Vendor Code</description>
        <formula>Part_Number__c  &amp; Vendor_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Merge of Part Number and Vendor Code</inlineHelpText>
        <label>Part ID</label>
        <type>Text</type>
    </fields>
    <label>Part</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

bppackaging/src/objects/Part_FIFO_Bucket__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Part FIFO Buckets</relationshipLabel>
        <relationshipName>Part_FIFO_Buckets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qty_In__c</fullName>
        <label>Qty In</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Qty_Out__c</fullName>
        <label>Qty Out</label>
        <summarizedField>Part_FIFO_Bucket_Activity_Line_Item__c.Qty_Out__c</summarizedField>
        <summaryForeignKey>Part_FIFO_Bucket_Activity_Line_Item__c.Part_FIFO_Bucket__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <formula>Cost__c  *  Remaining_Qty__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Part</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <formula>if(LEN(TEXT(Part_Adjust_Number__c)) == 5, &apos;PA-&apos; &amp;  TEXT(Part_Adjust_Number__c),
  if(LEN(TEXT(Part_Adjust_Number__c)) == 4, &apos;PA-0&apos; &amp;  TEXT(Part_Adjust_Number__c),
  if(LEN(TEXT(Part_Adjust_Number__c)) == 3, &apos;PA-00&apos; &amp;  TEXT(Part_Adjust_Number__c),
  if(LEN(TEXT(Part_Adjust_Number__c)) == 2, &apos;PA-000&apos; &amp;  TEXT(Part_Adjust_Number__c),
  if(LEN(TEXT(Part_Adjust_Number__c)) == 1, &apos;PA-0000&apos; &amp;  TEXT(Part_Adjust_Number__c),&apos;&apos;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoicing_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Invoicing Header</label>
        <referenceTo>Vendor_Invoicing_Header__c</referenceTo>
        <relationshipLabel>Part FIFO Buckets</relationshipLabel>
        <relationshipName>Part_FIFO_Buckets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Receiving_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Receiving Header</label>
        <referenceTo>Vendor_Receiving_Header__c</referenceTo>
        <relationshipLabel>Part FIFO Buckets</relationshipLabel>
        <relationshipName>Part_FIFO_Buckets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Part FIFO Bucket</label>
    <nameField>
        <displayFormat>PBN-{00000000}</displayFormat>
        <label>Part FIFO Bucket  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Part FIFO Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bppackaging/src/objects/Part_FIFO_Bucket_Activity_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>CO_Invoice_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Invoice Header</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>Part FIFO Bucket Activity Line Items</relationshipLabel>
        <relationshipName>Part_FIFO_Bucket_Activity_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CO_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Line Item</label>
        <referenceTo>CO_Line_Item__c</referenceTo>
        <relationshipName>Part_FIFO_Bucket_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Part_Adjustment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Adjustment</label>
        <referenceTo>Part_FIFO_Bucket__c</referenceTo>
        <relationshipLabel>Part FIFO Bucket Activity Line Items (Part Adjustment)</relationshipLabel>
        <relationshipName>Part_FIFO_Bucket_Activity_Line_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Part_FIFO_Bucket__c</fullName>
        <label>Part FIFO Bucket</label>
        <referenceTo>Part_FIFO_Bucket__c</referenceTo>
        <relationshipLabel>Part FIFO Bucket Activity Line Items</relationshipLabel>
        <relationshipName>Part_FIFO_Bucket_Activity_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Qty_Out__c</fullName>
        <label>Qty Out</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Part</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <label>Unique Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Part FIFO Bucket Activity Line Item</label>
    <nameField>
        <displayFormat>PBNLI-{00000000}</displayFormat>
        <label>Part FIFO Bucket Activity Line Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Part FIFO Bucket Activity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

bppackaging/src/objects/Vendor_Invoicing_Header__c.object
<CustomObject>
    <fields>
        <fullName>Total__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <label>Vendor Invoicing Header</label>
    <nameField>
        <displayFormat>VI-{0000000}</displayFormat>
        <label>Vendor Invoicing Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoicing Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bppackaging/src/objects/Vendor_Receiving_Group__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cost</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Vendor Receiving Group Parts</relationshipLabel>
        <relationshipName>Vendor_Receiving_Group_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vendor_Receiving_Header__c</fullName>
        <label>Vendor Receiving Header</label>
        <referenceTo>Vendor_Receiving_Header__c</referenceTo>
        <relationshipLabel>Vendor Receiving Groups</relationshipLabel>
        <relationshipName>Vendor_Receiving_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vendor Receiving Group</label>
    <nameField>
        <displayFormat>VG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Receiving Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

bppackaging/src/classes/AccountingDataMigrationFifoBucket.cls
global with sharing class AccountingDataMigrationFifoBucket implements Database.batchable<sObject>,Database.Stateful {
	// Accounting synch data migration "General Journal Entries" object name
	public static final String ACCOUNTING_OBJECT_NAME = 'General Journal Entries';
	
	// Batch size
	private static final Integer BATCH_SIZE = 1000;
	
	// Data string for all exporatble Vendor Receiving data
	private String generalJournalEntriesData;
	
	// Query string
	private string query;
	
	
	private String value;
	
	
	private String costValue;
	
	// DateTime value for last synched
	private DateTime Last_Synched_Date;
	
	// Index value to maintain total records count
	private integer indexVal;
	
	// "Vendor Receiving card" record of Accounting Data Migration object
	private Accounting_Data_Migration__c dataMigration;
	
	// Boolean to show if to export all records data
	private boolean exportAllData = false;
	
	/**
     * Name: AccountingDataMigrationvendorReceiving
     * Desc: Constructor to start the batch for data export
    **/
	global AccountingDataMigrationFifoBucket(List<Id> recordIds,boolean exportAllData) {
		if(AccessControl.ifObjectFieldIsAccessible('Accounting_Data_Migration__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
		if(AccessControl.ifObjectFieldIsCreateable('Accounting_Data_Migration__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_CREATEABLE); }
		if(AccessControl.ifObjectFieldIsUpdateable('Accounting_Data_Migration__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_UPDATEABLE); }
		
		this.exportAllData = exportAllData;
		generalJournalEntriesData = '';
		indexVal = 1;
		
		// Get the "Vendor Receiving card" record from Accounting Data Migration object
    	try{
    		dataMigration = [Select Id, Last_Synched_Date__c from Accounting_Data_Migration__c where Object_Name__c =: ACCOUNTING_OBJECT_NAME];
    	} catch(QueryException e) {
    		dataMigration = new Accounting_Data_Migration__c(Object_Name__c = AccountingDataMigrationFifoBucket.ACCOUNTING_OBJECT_NAME);
    	}
    	//system.assert(false,dataMigration.Last_Synched_Date__c);
    	//Last synched date value by which we need to filter Accounts data
		// Set Last Synched date for migration record
		//Last_Synched_Date = dataMigration.Last_Synched_Date__c;
		//System.assert(false,Last_Synched_Date);
    	//dataMigration.Last_Synched_Date__c = Datetime.now();
    	
    	query = createQuery(recordIds);
	}
	
	/**
     * Name: executeDataMigrationBatch
     * Desc: Constructor to start the batch for data export
    **/
	public static Id executeDataMigrationBatch(Integer batchSize, List<Id> recordIds, boolean exportAllData) {
		Id batchId = Database.executeBatch(new AccountingDataMigrationFifoBucket(recordIds, exportAllData), batchSize);
		return batchId;
	}
	
	/**
     * Name: start
     * Desc: Batch start method - Create query and execute query locator
     * @param: 
     * @return: Database.QueryLocator
    **/
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}
	
	/**
     * Name: execute
     * Desc: Batch execute method to process the exported data records
     * @param:	1. Database.BatchableContext BC
     * 			2. List<sObject> scope
     * @return:
    **/
	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		if(AccessControl.ifObjectFieldIsUpdateable('Vendor_Receiving_Group__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_UPDATEABLE); }
		if(AccessControl.ifObjectFieldIsAccessible('GL_Account__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }

		value = '{} \n';
		value +=  'Journal Number\tDate\tMemo\tGST (BAS) Reporting\tInclusive\tAccount Number\tIs Credit\tAmount\tTax Code\tAllocation Memo\n\n';
		costValue = '{} \n';
		costValue +=  'Journal Number\tDate\tMemo\tGST (BAS) Reporting\tInclusive\tAccount Number\tIs Credit\tAmount\tTax Code\tAllocation Memo\n\n';
		List<Part_FIFO_Bucket__c> partFifoRecords = (List<Part_FIFO_Bucket__c>) scope;
		
		if(partFifoRecords.size() > 0){
	    	// Map of General Journal Entries records for all applicable saleforce customer records (a map of VR sf fields to equivalent values)
	    	List<AccountingPartFIFOWrapper> generalJournalEntryRecords = new List<AccountingPartFIFOWrapper>();
	    	
	    	// GL Accounts for deposit
	    	List<GL_Account__c> glAccounts = [Select Id, MYOB_Account_Name__c, MYOB_Account_Number__c, Type__c from GL_Account__c Where Type__c LIKE '%Inventory%'];
	    	Map<String, String> GLAccountMap = new Map<String, String>();
	    	for(GL_Account__c glAcc : glAccounts){
	    		GLAccountMap.put(glAcc.Type__c, glAcc.MYOB_Account_Number__c);
	    	}
	    	
	    	String StockAdjustmentValue = (GLAccountMap.containsKey('Received Inventory Accrual')) ? GLAccountMap.get('Received Inventory Accrual') : '';
	    	String costRecQuery = 'Select Name, Part_FIFO_Bucket__c, Qty_Out__c,CO_Line_Item__c,Part_Adjustment__r.Unique_Id__c,Type__c, Part_FIFO_Bucket__r.Part__r.Category__r.Inventory_GL__c, Part_FIFO_Bucket__r.Part__r.Part_ID__c, Part_FIFO_Bucket__r.Cost__c, Part_Adjustment__c,CreatedDate, Reference__c, Unique_Id__c,Part_FIFO_Bucket__r.Qty_In__c, CO_Invoice_Header__c, LastModifiedDate From Part_FIFO_Bucket_Activity_Line_Item__c where Reference__c = \'Cost Adjustment\' AND Part_FIFO_Bucket__r.Reference__c != \'Cost Adjustment\' ';
	    	String countRecQuery = 'Select Name, Part_FIFO_Bucket__c, Qty_Out__c,CO_Line_Item__c,Part_Adjustment__r.Unique_Id__c,Type__c, Part_FIFO_Bucket__r.Part__r.Category__r.Inventory_GL__c, Part_FIFO_Bucket__r.Part__r.Part_ID__c, Part_FIFO_Bucket__r.Cost__c, Part_Adjustment__c,CreatedDate, Reference__c, Unique_Id__c,Part_FIFO_Bucket__r.Qty_In__c, CO_Invoice_Header__c, LastModifiedDate From Part_FIFO_Bucket_Activity_Line_Item__c where Reference__c = \'Count Adjustment\' AND Part_FIFO_Bucket__r.Reference__c != \'Count Adjustment\'';
	    	
	    	if(Last_Synched_Date != null){
    		//system.assert(false,Last_Synched_Date );
    			costRecQuery += 'And LastModifiedDate >: Last_Synched_Date';
    			countRecQuery += 'And LastModifiedDate >: Last_Synched_Date';
    		}
	    	
			List<Part_FIFO_Bucket_Activity_Line_Item__c> costAdjustRec = Database.query(costRecQuery);
			List<Part_FIFO_Bucket_Activity_Line_Item__c> countAdjustRec = Database.query(countRecQuery);
		 
		
	    for(Part_FIFO_Bucket__c partFIFOBucketItem  :  partFifoRecords){
	    	if(partFIFOBucketItem.Reference__c.toLowerCase().indexOf('Count Adjustment'.toLowerCase()) != -1){
	        	 value += AccountingPartFIFOWrapper.AccountingPartFIFOWrapperRec(partFIFOBucketItem, StockAdjustmentValue);
	        	 value += '\n\n';
	        	for(Part_FIFO_Bucket_Activity_Line_Item__c  fifoActivityRec : partFIFOBucketItem.Part_FIFO_Bucket_Activity_Line_Items__r ){
	        		if(String.isNotBlank(fifoActivityRec.Reference__c)&& fifoActivityRec.Reference__c.toLowerCase().indexOf('Count Adjustment'.toLowerCase()) != -1){
		        		value += AccountingPartFIFOWrapper.PartFIFOActivityLineItemRec(fifoActivityRec, partFIFOBucketItem, StockAdjustmentValue);
		        		value += '\n\n';
	        		}
	        	}
	        		//value += '';
	        		//value += '\n';
		    	system.debug(value);
	    	} else if((partFIFOBucketItem.Reference__c.toLowerCase().indexOf('re'.toLowerCase()) != -1)||(partFIFOBucketItem.Reference__c.toLowerCase().indexOf('Cost Adjustment'.toLowerCase()) != -1)){
	    		costValue += AccountingPartFIFOWrapper.AccountingPartFIFOWrapperCostRec(partFIFOBucketItem, StockAdjustmentValue );
	        	 costValue += '\n\n';
	        	for(Part_FIFO_Bucket_Activity_Line_Item__c  activityRec : partFIFOBucketItem.Part_FIFO_Bucket_Activity_Line_Items__r ){
	        		if(String.isNotBlank(activityRec.Reference__c)&& ((activityRec.Reference__c.toLowerCase().indexOf('Cost Adjustment'.toLowerCase()) != -1) || (activityRec.Reference__c.toLowerCase().indexOf('Pre'.toLowerCase()) != -1))){
		        		costValue += AccountingPartFIFOWrapper.PartFIFOActivityCostLineItemRec(activityRec,partFIFOBucketItem, StockAdjustmentValue);
		        		costValue += '\n\n';
	        		}
	        	}
	    	}  
	    		
	    	}
	    	
	    	if(costAdjustRec.size()>0){
	    		for(Part_FIFO_Bucket_Activity_Line_Item__c  activityRec : costAdjustRec ){
	        		costValue += AccountingPartFIFOWrapper.PartFIFOActivityCostAdjustItemRec(activityRec, StockAdjustmentValue);
	        		costValue += '\n\n';
	        	}
	    	}
	    	
	    	if(countAdjustRec.size()>0){
	    		for(Part_FIFO_Bucket_Activity_Line_Item__c  countRec : countAdjustRec ){
	        		value += AccountingPartFIFOWrapper.PartFIFOActivityCountAdjustItemRec(countRec,StockAdjustmentValue );
	        		value += '\n\n';
	        	}
	    	}
		}
		//System.assert(false,value);
	    	// Now create a string for list of General Journal Entries records so as to convert in format of importable text file for accounting software
    		//generalJournalEntriesData += createImportableTextForGeneralJournalEntries(generalJournalEntryRecords);
    	}
	
	/**
     * Name: finish 
     * Desc: Batch finish method to insert a attachment for exported data in text file
     * @param:	1. Database.BatchableContext BC
     * @return:
    **/
	global void finish(Database.BatchableContext BC) {
		List<Attachment> attachmentsList = new List<Attachment>();
		
    	//upsert dataMigration;
    	
    	Attachment attachment = new Attachment();
		attachment.Body = Blob.valueOf(value);
    	attachment.Name = 'GENERAL_JOURNAL_COUNT_ADJUSTMENT' + DateTime.now().format(DataExportService.fileDateTimeFormat) + '.TXT';
    	attachment.ParentId = dataMigration.Id;  
    	attachment.ContentType = 'text/plain';
    	attachmentsList.add(attachment);
    	
    	attachment = new Attachment();
    	attachment.Body = Blob.valueOf(costValue);
    	attachment.Name = 'GENERAL_JOURNAL_COST_ADJUSTMENT' + DateTime.now().format(DataExportService.fileDateTimeFormat) + '.TXT';
    	attachment.ParentId = dataMigration.Id;  
    	attachment.ContentType = 'text/plain';
    	attachmentsList.add(attachment);
    	
    	if(attachmentsList.size() > 0){
    		insert attachmentsList;
    	}
    	
    	// Execute next batch
    	if(exportAllData){
    		AccountingDataMigrationVendorInvoice.executeDataMigrationBatch(200, null, exportAllData);
    	}
	}
	
	/**
     * Name: createQuery
     * Desc: Method to create a query string for customer orders
     * @param:
     * @return: String
    **/
	public String createQuery(List<Id> recordIds) {
		// Get all vr to be synched here
    	String vrsQuery = 'SELECT ';
    	
    	String standardFieldsQuery = 'Id, Name, CreatedDate ';
    	
    	String customFieldsQuery = ' , Vendor_Receiving_Header__c, Vendor_Invoicing_Header__c, Unique_Id__c, Total__c, Source_Name__c, Remaining_Qty__c, Reference__c,Part__r.Part_Number__c, Type__c, Qty_Out__c, Qty_In__c ,Customer_Return__c, Part__c, Part_Adjust_Number__c, Part__r.Part_ID__c, Is_FIFO_Bucket__c,Part__r.Category__r.Inventory_GL__c, Cost__c';
    	customFieldsQuery += ' ,  (Select Name, Part_FIFO_Bucket__c, Qty_Out__c,CO_Line_Item__c,Part_Adjustment__r.Unique_Id__c,Type__c, Part_Adjustment__c,CreatedDate, Reference__c, Unique_Id__c, CO_Invoice_Header__c From Part_FIFO_Bucket_Activity_Line_Items__r)'; 
    	//customFieldsQuery += '';
    	
    	
    	String whereCondition = 'WHERE (Reference__c = \'Count Adjustment\'  OR Reference__c Like  \'re%\' OR Reference__c = \'Cost Adjustment\' )' ;
    	
    	if(Last_Synched_Date != null){
    		//system.assert(false,Last_Synched_Date );
    		whereCondition += 'And LastModifiedDate >: Last_Synched_Date';
    	}
    	if(recordIds != null && recordIds.size() > 0){
    		whereCondition += ' AND Id IN ' + recordIds;
    	}
    	
    	vrsQuery += standardFieldsQuery + customFieldsQuery + ' FROM Part_FIFO_Bucket__c ' + whereCondition + ' ORDER BY Name';
    	//system.assert(false,vrsQuery);
    	return vrsQuery;
	}
    
    
    
    
    
}