bppackaging/src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bppackaging/src/objects/Part__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part_ID__c</fullName>
        <description>Merge of Part Number and Vendor Code</description>
        <formula>Part_Number__c  &amp; Vendor_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Merge of Part Number and Vendor Code</inlineHelpText>
        <label>Part ID</label>
        <type>Text</type>
    </fields>
    <label>Part</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

bppackaging/src/objects/Part_FIFO_Bucket__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Part FIFO Buckets</relationshipLabel>
        <relationshipName>Part_FIFO_Buckets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qty_In__c</fullName>
        <label>Qty In</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Qty_Out__c</fullName>
        <label>Qty Out</label>
        <summarizedField>Part_FIFO_Bucket_Activity_Line_Item__c.Qty_Out__c</summarizedField>
        <summaryForeignKey>Part_FIFO_Bucket_Activity_Line_Item__c.Part_FIFO_Bucket__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Source_Name__c</fullName>
        <label>Source Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <formula>if(LEN(TEXT(Part_Adjust_Number__c)) == 5, &apos;PA-&apos; &amp;  TEXT(Part_Adjust_Number__c),
  if(LEN(TEXT(Part_Adjust_Number__c)) == 4, &apos;PA-0&apos; &amp;  TEXT(Part_Adjust_Number__c),
  if(LEN(TEXT(Part_Adjust_Number__c)) == 3, &apos;PA-00&apos; &amp;  TEXT(Part_Adjust_Number__c),
  if(LEN(TEXT(Part_Adjust_Number__c)) == 2, &apos;PA-000&apos; &amp;  TEXT(Part_Adjust_Number__c),
  if(LEN(TEXT(Part_Adjust_Number__c)) == 1, &apos;PA-0000&apos; &amp;  TEXT(Part_Adjust_Number__c),&apos;&apos;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique Id</label>
        <type>Text</type>
    </fields>
    <label>Part FIFO Bucket</label>
    <nameField>
        <displayFormat>PBN-{00000000}</displayFormat>
        <label>Part FIFO Bucket  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Part FIFO Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bppackaging/src/objects/Part_FIFO_Bucket_Activity_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Part_Adjustment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Adjustment</label>
        <referenceTo>Part_FIFO_Bucket__c</referenceTo>
        <relationshipLabel>Part FIFO Bucket Activity Line Items (Part Adjustment)</relationshipLabel>
        <relationshipName>Part_FIFO_Bucket_Activity_Line_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Part_FIFO_Bucket__c</fullName>
        <label>Part FIFO Bucket</label>
        <referenceTo>Part_FIFO_Bucket__c</referenceTo>
        <relationshipLabel>Part FIFO Bucket Activity Line Items</relationshipLabel>
        <relationshipName>Part_FIFO_Bucket_Activity_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Qty_Out__c</fullName>
        <label>Qty Out</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <label>Unique Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Part FIFO Bucket Activity Line Item</label>
    <nameField>
        <displayFormat>PBNLI-{00000000}</displayFormat>
        <label>Part FIFO Bucket Activity Line Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Part FIFO Bucket Activity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

bppackaging/src/classes/AccountingPartFIFOWrapper.cls
public with sharing class AccountingPartFIFOWrapper {
    public static String FIFOBucketId;
	public static String UniqueId;
	public static String CreatedDate;
	public static String PartId;
	public static String PartName;
	public static String Gst;
	public static String Inclusive;
	public static String Category;
	public static String IsCredit;
	public static Decimal Amount;
	public static String TaxCode;
	public static String AllocationMemo; 
	public static String SourceName;
	//public final static String StockAdjustmentValue = '2-1530';
	
	
	//public List<PartFIFOActivityLineItem> PartFIFOActivityLineItemList = new List<PartFIFOActivityLineItem>();
	
	public static string  AccountingPartFIFOWrapperRec(Part_FIFO_Bucket__c partFifoBucketRec, String StockAdjustmentValue){
		
		UniqueId = partFifoBucketRec.Unique_Id__c;
		CreatedDate = partFifoBucketRec.CreatedDate!= null ? partFifoBucketRec.CreatedDate.format(DataExportService.dateFormat) : System.now().format(DataExportService.dateFormat) ;
		FIFOBucketId =  partFifoBucketRec.Id;
		SourceName = partFifoBucketRec.Source_Name__c;
		
			
		Gst = 'P';
		Inclusive = 'X';
		Category = (partFifoBucketRec.Part__r.Category__r != null && partFifoBucketRec.Part__r.Category__r.Inventory_GL__c != null) ? partFifoBucketRec.Part__r.Category__r.Inventory_GL__c : ''; 
		IsCredit = 'N';
		PartId = partFifoBucketRec.Part__r.Part_ID__c+ ';' + 'Count Adjustment';
		Amount = ((partFifoBucketRec.Qty_In__c == null? 0 :partFifoBucketRec.Qty_In__c) * (partFifoBucketRec.Cost__c == null ? 0 : partFifoBucketRec.Cost__c)).setScale(2);
		AllocationMemo = partFifoBucketRec.Part__r.Part_ID__c + ' - increased by ' + (partFifoBucketRec.Qty_In__c==null? 0: partFifoBucketRec.Qty_In__c).setScale(2)  + '@$'+ (partFifoBucketRec.cost__c == null ?0:partFifoBucketRec.cost__c).setScale(2);
		TaxCode = 'N-T';	
		 
		String value =  UniqueId + '\t' + CreatedDate + '\t'+ partId+ '\t'+Gst+'\t'+ Inclusive+'\t'+Category+'\t' + IsCredit+'\t'+ '$'+Amount+'\t'+ TaxCode+'\t'+AllocationMemo+'\n';
		value  += UniqueId + '\t' + CreatedDate + '\t'+ partId+ '\t'+Gst+'\t'+ Inclusive+'\t'+StockAdjustmentValue+'\tY\t'+ '$'+Amount+'\t'+ TaxCode+'\t'+AllocationMemo;
		//System.assert(false,value);
		return value;
		
	}
	
	

	public static string PartFIFOActivityLineItemRec(Part_FIFO_Bucket_Activity_Line_Item__c partFifoActivityLineItemRec, Part_FIFO_Bucket__c partFifoBucketRec, String StockAdjustmentValue ){
		UniqueId = partFifoActivityLineItemRec.Unique_Id__c ==  NULL ? partFifoBucketRec.Unique_Id__c: partFifoActivityLineItemRec.Unique_Id__c ;
		CreatedDate = partFifoActivityLineItemRec.CreatedDate!= null ? partFifoActivityLineItemRec.CreatedDate.format(DataExportService.dateFormat) : System.now().format(DataExportService.dateFormat) ;
		FIFOBucketId =  partFifoActivityLineItemRec.Id;
		SourceName = partFifoBucketRec.Source_Name__c;
		
			
		Gst = 'P';
		Inclusive = 'X';
		Category = (partFifoBucketRec.Part__r.Category__r != null && partFifoBucketRec.Part__r.Category__r.Inventory_GL__c != null) ? partFifoBucketRec.Part__r.Category__r.Inventory_GL__c : ''; 
		IsCredit = 'Y';
		PartId = partFifoBucketRec.Part__r.Part_ID__c+ ';' + 'Count Adjustment';
		Amount = ((partFifoActivityLineItemRec.Qty_Out__c == null? 0 :partFifoActivityLineItemRec.Qty_Out__c) * (partFifoBucketRec.Cost__c == null ? 0 : partFifoBucketRec.Cost__c)).setScale(2);
		AllocationMemo = partFifoBucketRec.Part__r.Part_ID__c + ' - reduced by ' + (partFifoActivityLineItemRec.Qty_Out__c == null? 0 :partFifoActivityLineItemRec.Qty_Out__c).setScale(2)  + '@$'+ (partFifoBucketRec.cost__c == null ?0:partFifoBucketRec.cost__c).setScale(2);
		TaxCode = 'N-T';	
		 
		String value =  UniqueId + '\t' + CreatedDate + '\t'+ partId+ '\t'+Gst+'\t'+ Inclusive+'\t'+Category+'\t' + IsCredit+'\t'+'$'+ Amount+'\t'+ TaxCode+'\t'+AllocationMemo+'\n';
		value += UniqueId + '\t' + CreatedDate + '\t'+ partId+ '\t'+Gst+'\t'+ Inclusive+'\t'+StockAdjustmentValue+'\tN\t'+'$'+ Amount+'\t'+ TaxCode+'\t'+AllocationMemo;
		return value;
	}
		
		
		
	public static string  AccountingPartFIFOWrapperCostRec(Part_FIFO_Bucket__c partFifoBucketRec, String StockAdjustmentValue){
		
		UniqueId = partFifoBucketRec.Unique_Id__c;
		CreatedDate = partFifoBucketRec.CreatedDate!= null ? partFifoBucketRec.CreatedDate.format(DataExportService.dateFormat) : System.now().format(DataExportService.dateFormat) ;
		FIFOBucketId =  partFifoBucketRec.Id;
		SourceName = partFifoBucketRec.Source_Name__c;
		Gst = 'P';
		Inclusive = 'X';
		Category = (partFifoBucketRec.Part__r.Category__r != null && partFifoBucketRec.Part__r.Category__r.Inventory_GL__c != null) ? partFifoBucketRec.Part__r.Category__r.Inventory_GL__c : ''; 
		IsCredit = 'N';
		PartId = partFifoBucketRec.Part__r.Part_ID__c+ ';' + 'Cost Adjustment';
		Amount = ((partFifoBucketRec.Qty_In__c == null? 0 :partFifoBucketRec.Qty_In__c) * (partFifoBucketRec.Cost__c == null ? 0 : partFifoBucketRec.Cost__c)).setScale(2);
		AllocationMemo = partFifoBucketRec.Part__r.Part_ID__c + ' - increased by ' + (partFifoBucketRec.Qty_In__c==null? 0: partFifoBucketRec.Qty_In__c).setScale(2)  + '@$'+ (partFifoBucketRec.cost__c == null ?0:partFifoBucketRec.cost__c).setScale(2);
		TaxCode = 'N-T';	
	 
		String value =  UniqueId + '\t' + CreatedDate + '\t'+ partId+ '\t'+Gst+'\t'+ Inclusive+'\t'+Category+'\t' + IsCredit+'\t'+'$'+ Amount+'\t'+ TaxCode+'\t'+AllocationMemo+'\n';
		value  += UniqueId + '\t' + CreatedDate + '\t'+ partId+ '\t'+Gst+'\t'+ Inclusive+'\t'+StockAdjustmentValue+'\tY\t'+'$'+ Amount+'\t'+ TaxCode+'\t'+AllocationMemo;
		//System.assert(false,value);
		return value;
		
	}
	
	

	public static string PartFIFOActivityCostLineItemRec(Part_FIFO_Bucket_Activity_Line_Item__c partFifoActivityLineItemRec, Part_FIFO_Bucket__c partFifoBucketRec, String StockAdjustmentValue ){
		UniqueId = partFifoActivityLineItemRec.Unique_Id__c ==  NULL ? partFifoBucketRec.Unique_Id__c: partFifoActivityLineItemRec.Unique_Id__c ;
		CreatedDate = partFifoActivityLineItemRec.CreatedDate!= null ? partFifoActivityLineItemRec.CreatedDate.format(DataExportService.dateFormat) : System.now().format(DataExportService.dateFormat) ;
		FIFOBucketId =  partFifoBucketRec.Id;
		SourceName = partFifoBucketRec.Source_Name__c;
		
			
		Gst = 'P';
		Inclusive = 'X';
		Category = (partFifoBucketRec.Part__r.Category__r != null && partFifoBucketRec.Part__r.Category__r.Inventory_GL__c != null) ? partFifoBucketRec.Part__r.Category__r.Inventory_GL__c : ''; 
		IsCredit = 'Y';
		PartId = partFifoBucketRec.Part__r.Part_ID__c+ ';' + 'Cost Adjustment';
		Amount = ((partFifoActivityLineItemRec.Qty_Out__c == null? 0 :partFifoActivityLineItemRec.Qty_Out__c) * (partFifoBucketRec.Cost__c == null ? 0 : partFifoBucketRec.Cost__c)).setScale(2);
		AllocationMemo = partFifoBucketRec.Part__r.Part_ID__c + ' - reduced by ' + (partFifoBucketRec.Qty_Out__c == null? 0 :partFifoBucketRec.Qty_Out__c).setScale(2)  + '@$'+ (partFifoBucketRec.cost__c == null ?0:partFifoBucketRec.cost__c).setScale(2);
		TaxCode = 'N-T';	
		 
		String value =  UniqueId + '\t' + CreatedDate + '\t'+ partId+ '\t'+Gst+'\t'+ Inclusive+'\t'+Category+'\t' + IsCredit+'\t'+'$'+ Amount+'\t'+ TaxCode+'\t'+AllocationMemo+'\n';
		value += UniqueId + '\t' + CreatedDate + '\t'+ partId+ '\t'+Gst+'\t'+ Inclusive+'\t'+StockAdjustmentValue+'\tN\t'+'$'+ Amount+'\t'+ TaxCode+'\t'+AllocationMemo;
		return value;
	}
	
	
	
	public static string PartFIFOActivityCostAdjustItemRec(Part_FIFO_Bucket_Activity_Line_Item__c partFifoActivityLineItemRec, String StockAdjustmentValue ){
		UniqueId = partFifoActivityLineItemRec.Unique_Id__c == null ? partFifoActivityLineItemRec.Part_Adjustment__r.Unique_Id__c :partFifoActivityLineItemRec.Unique_Id__c  ;
		CreatedDate = partFifoActivityLineItemRec.CreatedDate!= null ? partFifoActivityLineItemRec.CreatedDate.format(DataExportService.dateFormat) : System.now().format(DataExportService.dateFormat) ;
		FIFOBucketId =  partFifoActivityLineItemRec.Id;
		//SourceName = partFifoBucketRec.Source_Name__c;
		
			
		Gst = 'P';
		Inclusive = 'X';
		Category = (partFifoActivityLineItemRec.Part_FIFO_Bucket__r.Part__r.Category__r != null && partFifoActivityLineItemRec.Part_FIFO_Bucket__r.Part__r.Category__r.Inventory_GL__c != null) ? partFifoActivityLineItemRec.Part_FIFO_Bucket__r.Part__r.Category__r.Inventory_GL__c : ''; 
		IsCredit = 'Y';
		PartId = partFifoActivityLineItemRec.Part_FIFO_Bucket__r.Part__r.Part_ID__c+ ';' + 'Cost Adjustment';
		Amount = ((partFifoActivityLineItemRec.Qty_Out__c == null? 0 :partFifoActivityLineItemRec.Qty_Out__c) * (partFifoActivityLineItemRec.Part_FIFO_Bucket__r.Cost__c == null ? 0 : partFifoActivityLineItemRec.Part_FIFO_Bucket__r.Cost__c)).setScale(2);
		AllocationMemo = partFifoActivityLineItemRec.Part_FIFO_Bucket__r.Part__r.Part_Id__c + ' - reduced by ' + (partFifoActivityLineItemRec.Qty_Out__c == null? 0 :partFifoActivityLineItemRec.Qty_Out__c).setScale(2)  + '@$'+ (partFifoActivityLineItemRec.Part_FIFO_Bucket__r.cost__c == null ?0:partFifoActivityLineItemRec.Part_FIFO_Bucket__r.cost__c).setScale(2);
		TaxCode = 'N-T';	
		 
		String value =  UniqueId + '\t' + CreatedDate + '\t'+ partId+ '\t'+Gst+'\t'+ Inclusive+'\t'+Category+'\t' + IsCredit+'\t'+'$'+ Amount+'\t'+ TaxCode+'\t'+AllocationMemo+'\n';
		value += UniqueId + '\t' + CreatedDate + '\t'+ partId+ '\t'+Gst+'\t'+ Inclusive+'\t'+StockAdjustmentValue+'\tN\t'+'$'+ Amount+'\t'+ TaxCode+'\t'+AllocationMemo;
		return value;
	}
	
	
	public static string PartFIFOActivityCountAdjustItemRec(Part_FIFO_Bucket_Activity_Line_Item__c partFifoActivityLineItemRec, String StockAdjustmentValue ){
		UniqueId = partFifoActivityLineItemRec.Unique_Id__c == null ? partFifoActivityLineItemRec.Part_Adjustment__r.Unique_Id__c :partFifoActivityLineItemRec.Unique_Id__c  ;
		CreatedDate = partFifoActivityLineItemRec.CreatedDate!= null ? partFifoActivityLineItemRec.CreatedDate.format(DataExportService.dateFormat) : System.now().format(DataExportService.dateFormat) ;
		FIFOBucketId =  partFifoActivityLineItemRec.Id;
		//SourceName = partFifoBucketRec.Source_Name__c;
		
			
		Gst = 'P';
		Inclusive = 'X';
		Category = (partFifoActivityLineItemRec.Part_FIFO_Bucket__r.Part__r.Category__r != null && partFifoActivityLineItemRec.Part_FIFO_Bucket__r.Part__r.Category__r.Inventory_GL__c != null) ? partFifoActivityLineItemRec.Part_FIFO_Bucket__r.Part__r.Category__r.Inventory_GL__c : ''; 
		IsCredit = 'Y';
		PartId = partFifoActivityLineItemRec.Part_FIFO_Bucket__r.Part__r.Part_ID__c+ ';' + 'Count Adjustment';
		Amount = ((partFifoActivityLineItemRec.Qty_Out__c == null? 0 :partFifoActivityLineItemRec.Qty_Out__c) * (partFifoActivityLineItemRec.Part_FIFO_Bucket__r.Cost__c == null ? 0 : partFifoActivityLineItemRec.Part_FIFO_Bucket__r.Cost__c)).setScale(2);
		AllocationMemo = partFifoActivityLineItemRec.Part_FIFO_Bucket__r.Part__r.Part_Id__c + ' - reduced by ' + (partFifoActivityLineItemRec.Qty_Out__c == null? 0 :partFifoActivityLineItemRec.Qty_Out__c).setScale(2)  + '@$'+ (partFifoActivityLineItemRec.Part_FIFO_Bucket__r.cost__c == null ?0:partFifoActivityLineItemRec.Part_FIFO_Bucket__r.cost__c).setScale(2);
		TaxCode = 'N-T';	
		 
		String value =  UniqueId + '\t' + CreatedDate + '\t'+ partId+ '\t'+Gst+'\t'+ Inclusive+'\t'+Category+'\t' + IsCredit+'\t'+'$'+ Amount+'\t'+ TaxCode+'\t'+AllocationMemo+'\n';
		value += UniqueId + '\t' + CreatedDate + '\t'+ partId+ '\t'+Gst+'\t'+ Inclusive+'\t'+StockAdjustmentValue+'\tN\t'+'$'+Amount+'\t'+ TaxCode+'\t'+AllocationMemo;
		return value;
	}
}