bppackaging/src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Country</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bppackaging/src/classes/Country.cls
/**
 * Author: Tarun Khandelwal
 * Since: May 25, 2015
 * Name: Country
 * Description: Apex class to handle JSON related oprations of Country object. (Used In Kendo)
**/
public with sharing class Country {
	
	// Country Name
	public String CountryName;
	
	// Default
	public Boolean IsDefault;
	
	// Id
	public String Id;
	
	// Constructor
    public Country(Country__c countryRec) {
    	this.CountryName = countryRec.Name__c;
    	this.IsDefault = countryRec.Default__c;
    	this.Id = countryRec.Id;
    }
    
    /**
     * Name: fieldsList
     * Desc: Method Which contains all the field list to be quried
     * @param:  
     * @return: List<String> - Fields List
    **/
    public static List<String> fieldsList(){
        List<String> countryFields = new List<String>{ 'Id',
                                                    'Name__c', 
                                                    'Default__c',
                                                    'Visible__c'
                                                };
        return countryFields;
    }
}