bppackaging/src/objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>State/Province</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

bppackaging/src/classes/State.cls
/**
 * Author: Tarun Khandelwal
 * Since: May 25, 2015
 * Name: State
 * Description: Apex class to handle JSON related oprations of State object.
**/
public with sharing class State {
		
	// State Name
	public String StateName;
	
	// Default
	public Boolean IsDefault;
	
	// Id
	public String Id;
	
	// Constructor
    public State(State__c stateRec) {
    	this.StateName = stateRec.Name__c;
    	this.IsDefault = stateRec.Default__c;
    	this.Id = stateRec.Id;
    }
		
	/**
     * Name: fieldsList
     * Desc: Method Which contains all the field list to be quried
     * @param:  
     * @return: List<String> - Fields List
    **/
    public static List<String> fieldsList(){
        List<String> stateFields = new List<String>{ 'Id',
                                                    'Name__c', 
                                                    'Default__c'
                                                };
        return stateFields;
    }	
		
		
	
}