bppackaging/src/objects/Vendor_Order_Header__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vendor Order Header</label>
    <nameField>
        <displayFormat>VO-{00000000}</displayFormat>
        <label>Vendor Order Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bppackaging/src/classes/VendorOrderHeaderTriggerTest.cls
@isTest
private class VendorOrderHeaderTriggerTest {

    static testMethod void testUpdateVendorOrderHeader(){
    	
        Vendor_Order_Header__c voHeader = new Vendor_Order_Header__c(Status__c = 'Open');
        insert voHeader;
        
        voHeader.Status__c = 'Locked';
        update voHeader;
        
        voHeader = [Select id, Name, Status__c from Vendor_Order_Header__c Limit 1];
        System.assert(String.valueOf(voHeader.Status__c).equalsIgnoreCase('Locked'), 'Record not updated successfully');
        
        List<Contact> accList = [select Id, Name from Contact limit 100];
		system.assertEquals(accList.size(), 0);
    }
}